permalink:           pretty

# Setup
title:               Zibo's Website
tagline:             "A digital collection of my work and life"
description:         "Navigation"
url:                 http://tonyzhang95.github.io
baseurl:             ""
paginate:            5
paginate_path:       "page:num"
plugins:             [jekyll-paginate]
gems:                [jekyll-paginate]

# Author
builder:             Zibo Zhang
linkedin:            https://www.linkedin.com/in/zibozhang
github:              https://github.com/tonyzhang95

# Custom vars
version:             0.0.2
